CREATE DATABASE testDB;
SHOW DATABASES;
DROP DATABASE testDB;
USE testDB;

CREATE TABLE CUSTOMERS(
   ID   INT              NOT NULL,
   NAME VARCHAR (20)     NOT NULL,
   AGE  INT              NOT NULL,
   ADDRESS  CHAR (25) ,
   SALARY   DECIMAL (18, 2),       
   PRIMARY KEY (ID)
);

#shows desription of table
 DESC CUSTOMERS;
 
 #to delete a table
 DROP TABLE CUSTOMERS;
 
 #to delete all the records
TRUNCATE TABLE  CUSTOMERS;

SELECT * FROM CUSTOMERS;

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (8, 'Ramesh', 32, 'Ahmedabad', 2000.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (7, 'Khilan', 25, 'Delhi', 1500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (3, 'kaushik', 23, 'Kota', 2000.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (4, 'Chaitali', 25, 'Mumbai', 6500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (5, 'Hardik', 27, 'Bhopal', 8500.00 );

INSERT INTO CUSTOMERS (ID,NAME,AGE,ADDRESS,SALARY)
VALUES (6, 'Komal', 22, 'MP', 4500.00 );

INSERT INTO CUSTOMERS 
VALUES (2, 'Muffy', 24, 'Indore', 10000.00 );

SELECT * FROM CUSTOMERS;
SELECT * FROM CUSTOMERS ORDER BY AGE;
#sorting with multiple columns: sort duplicates entries of first columns according to the second column
SELECT * FROM CUSTOMERS ORDER BY AGE,ADDRESS;

SELECT ID, NAME, SALARY FROM CUSTOMERS;

#SELECTS FORST 3 ROWS
SELECT * FROM CUSTOMERS LIMIT 3;

# BOTH QUERIES ARE SAME: SKIP FIRST 2 ROWS AND DISPLAY NEXT 3.
SELECT * FROM CUSTOMERS LIMIT 2,3;
SELECT * FROM CUSTOMERS LIMIT 3 OFFSET 2;

SELECT CONCAT_WS(', ', NAME, AGE) AS `Full` FROM CUSTOMERS;

SELECT ID, NAME, SALARY 
FROM CUSTOMERS
WHERE SALARY > 2000;

 SELECT ID, NAME, SALARY 
FROM CUSTOMERS
WHERE NAME = 'Hardik';

SELECT ID, NAME, SALARY 
FROM CUSTOMERS
WHERE SALARY > 2000 AND age < 25;

SELECT ID, NAME, SALARY 
FROM CUSTOMERS
WHERE SALARY > 2000 OR age < 25;

#for updating records
UPDATE CUSTOMERS
SET ADDRESS = 'Pune'
WHERE ID = 6;

UPDATE CUSTOMERS
SET NAME = 'Ramesh'
WHERE AGE = 25;

DELETE FROM CUSTOMERS
WHERE ID = 6;

#will delete all the records
DELETE FROM CUSTOMERS;

SELECT * FROM CUSTOMERS WHERE SALARY LIKE '200%';

SELECT DISTINCT NAME FROM CUSTOMERS;

SELECT  SUM(SALARY) AS TOTAL_SALARY,AGE FROM CUSTOMERS
GROUP BY AGE;

SELECT * FROM CUSTOMERS;
SELECT * FROM CUSTOMERS WHERE ADDRESS LIKE 'I%';
SELECT * FROM CUSTOMERS WHERE ADDRESS LIKE '[PB]%';

SELECT MIN(AGE) FROM CUSTOMERS;
SELECT ucase(ADDRESS) FROM CUSTOMERS;
SELECT substring(ADDRESS,1,3) FROM CUSTOMERS;
#find position of d in Indore;
Select INSTR(ADDRESS, BINARY'd') from CUSTOMERS where ADDRESS = 'Indore';
Select RTRIM(ADDRESS) AS RemovingWhiteSpacesFromRightSide from CUSTOMERS;
Select LTRIM(ADDRESS) AS RemovingWhiteSpacesFromLefttSide from CUSTOMERS;

# Write an SQL query that fetches the unique values of ADDRESS and prints its length.
SELECT DISTINCT ADDRESS,length(ADDRESS) from CUSTOMERS;

Select REPLACE(ADDRESS,'a','A') from CUSTOMERS;

SELECT * FROM CUSTOMERS WHERE ADDRESS IN('Mumbai','Indore');
SELECT * FROM CUSTOMERS WHERE ADDRESS='Mumbai';
SELECT COUNT(*) FROM CUSTOMERS WHERE ADDRESS='Mumbai';

#Add a column of type DATE called Birthday.
ALTER TABLE CUSTOMERS
ADD Birthday DATE;

#Delete the column Birthday
ALTER TABLE CUSTOMERS
DROP COLUMN Birthday;